#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Frenzyv1.Resource", IsApplication=true)]

namespace Frenzyv1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arriereplan = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Barbecue = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BigParty = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Brunch = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CreerMaSoiree = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Frenzy = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int InviterAmis = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int monoandroidsplash = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Party = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int SoireePosee = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Soirees = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int Alcool = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int Apero = 2131099665;
			
			// aapt resource value: 0x7f06009e
			public const int Barbecue = 2131099806;
			
			// aapt resource value: 0x7f06009f
			public const int BigParty = 2131099807;
			
			// aapt resource value: 0x7f060013
			public const int Brunch = 2131099667;
			
			// aapt resource value: 0x7f060003
			public const int CalendrierValider = 2131099651;
			
			// aapt resource value: 0x7f060084
			public const int Compte = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int Create = 2131099781;
			
			// aapt resource value: 0x7f060038
			public const int CreerSoiree = 2131099704;
			
			// aapt resource value: 0x7f060012
			public const int Extras = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int Food = 2131099668;
			
			// aapt resource value: 0x7f06009c
			public const int Friend = 2131099804;
			
			// aapt resource value: 0x7f060062
			public const int Invites13 = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int Invites18 = 2131099747;
			
			// aapt resource value: 0x7f060064
			public const int Invites23 = 2131099748;
			
			// aapt resource value: 0x7f060065
			public const int Invites28 = 2131099749;
			
			// aapt resource value: 0x7f060060
			public const int Invites3 = 2131099744;
			
			// aapt resource value: 0x7f060066
			public const int Invites35 = 2131099750;
			
			// aapt resource value: 0x7f060067
			public const int Invites45 = 2131099751;
			
			// aapt resource value: 0x7f060061
			public const int Invites7 = 2131099745;
			
			// aapt resource value: 0x7f060099
			public const int ListeBS = 2131099801;
			
			// aapt resource value: 0x7f06009b
			public const int ListeES = 2131099803;
			
			// aapt resource value: 0x7f06009a
			public const int ListeNS = 2131099802;
			
			// aapt resource value: 0x7f06000e
			public const int MonChoix = 2131099662;
			
			// aapt resource value: 0x7f060034
			public const int Nom = 2131099700;
			
			// aapt resource value: 0x7f060087
			public const int Profil = 2131099783;
			
			// aapt resource value: 0x7f060005
			public const int Sel1 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int Sel2 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int Sel3 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int Sel4 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int Sel5 = 2131099661;
			
			// aapt resource value: 0x7f060015
			public const int Select = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int Soft = 2131099664;
			
			// aapt resource value: 0x7f060002
			public const int SoireeCalendrier = 2131099650;
			
			// aapt resource value: 0x7f0600a0
			public const int SoireePosee = 2131099808;
			
			// aapt resource value: 0x7f060086
			public const int Soirees = 2131099782;
			
			// aapt resource value: 0x7f06009d
			public const int ToMenu = 2131099805;
			
			// aapt resource value: 0x7f060098
			public const int Total = 2131099800;
			
			// aapt resource value: 0x7f060052
			public const int btnBacon = 2131099730;
			
			// aapt resource value: 0x7f060049
			public const int btnBaguette = 2131099721;
			
			// aapt resource value: 0x7f060053
			public const int btnBeurre = 2131099731;
			
			// aapt resource value: 0x7f06006f
			public const int btnBiere = 2131099759;
			
			// aapt resource value: 0x7f060040
			public const int btnBiscuitsAp = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int btnBonbons = 2131099713;
			
			// aapt resource value: 0x7f060054
			public const int btnBrioches = 2131099732;
			
			// aapt resource value: 0x7f060042
			public const int btnCacahuetes = 2131099714;
			
			// aapt resource value: 0x7f060055
			public const int btnCafe = 2131099733;
			
			// aapt resource value: 0x7f060035
			public const int btnCalendrier = 2131099701;
			
			// aapt resource value: 0x7f06004a
			public const int btnChamallows = 2131099722;
			
			// aapt resource value: 0x7f060070
			public const int btnChamp = 2131099760;
			
			// aapt resource value: 0x7f06004b
			public const int btnChipolatas = 2131099723;
			
			// aapt resource value: 0x7f060043
			public const int btnChips = 2131099715;
			
			// aapt resource value: 0x7f060056
			public const int btnChocolat = 2131099734;
			
			// aapt resource value: 0x7f060044
			public const int btnCitrons = 2131099716;
			
			// aapt resource value: 0x7f060089
			public const int btnCoca = 2131099785;
			
			// aapt resource value: 0x7f060057
			public const int btnConfiture = 2131099735;
			
			// aapt resource value: 0x7f06004c
			public const int btnCotelettes = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int btnCourgettes = 2131099725;
			
			// aapt resource value: 0x7f060058
			public const int btnCroissants = 2131099736;
			
			// aapt resource value: 0x7f06008a
			public const int btnEau = 2131099786;
			
			// aapt resource value: 0x7f06008b
			public const int btnEauGazeuse = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int btnFanta = 2131099788;
			
			// aapt resource value: 0x7f060059
			public const int btnFromage = 2131099737;
			
			// aapt resource value: 0x7f060071
			public const int btnGet = 2131099761;
			
			// aapt resource value: 0x7f060072
			public const int btnGin = 2131099762;
			
			// aapt resource value: 0x7f060045
			public const int btnGlacons = 2131099717;
			
			// aapt resource value: 0x7f060073
			public const int btnJager = 2131099763;
			
			// aapt resource value: 0x7f06005a
			public const int btnJambon = 2131099738;
			
			// aapt resource value: 0x7f06008d
			public const int btnJusDeFruits = 2131099789;
			
			// aapt resource value: 0x7f06008f
			public const int btnJusDePamp = 2131099791;
			
			// aapt resource value: 0x7f060090
			public const int btnJusDePomme = 2131099792;
			
			// aapt resource value: 0x7f06008e
			public const int btnJusDorange = 2131099790;
			
			// aapt resource value: 0x7f06005b
			public const int btnLait = 2131099739;
			
			// aapt resource value: 0x7f060083
			public const int btnLogin = 2131099779;
			
			// aapt resource value: 0x7f060074
			public const int btnMalibu = 2131099764;
			
			// aapt resource value: 0x7f060075
			public const int btnMartini = 2131099765;
			
			// aapt resource value: 0x7f06004e
			public const int btnMerguez = 2131099726;
			
			// aapt resource value: 0x7f060037
			public const int btnNombreInvites = 2131099703;
			
			// aapt resource value: 0x7f060091
			public const int btnOasis = 2131099793;
			
			// aapt resource value: 0x7f06005c
			public const int btnOeufs = 2131099740;
			
			// aapt resource value: 0x7f060046
			public const int btnOlives = 2131099718;
			
			// aapt resource value: 0x7f060092
			public const int btnOrangina = 2131099794;
			
			// aapt resource value: 0x7f06005d
			public const int btnPainsChoco = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public const int btnPancakes = 2131099742;
			
			// aapt resource value: 0x7f060076
			public const int btnPassoa = 2131099766;
			
			// aapt resource value: 0x7f060077
			public const int btnPastis = 2131099767;
			
			// aapt resource value: 0x7f06004f
			public const int btnPiecesBrochette = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int btnPoivron = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int btnPommesDeTerre = 2131099729;
			
			// aapt resource value: 0x7f060078
			public const int btnPorto = 2131099768;
			
			// aapt resource value: 0x7f060093
			public const int btnRedBull = 2131099795;
			
			// aapt resource value: 0x7f060079
			public const int btnRhum = 2131099769;
			
			// aapt resource value: 0x7f060047
			public const int btnSaucisson = 2131099719;
			
			// aapt resource value: 0x7f06005f
			public const int btnSaumon = 2131099743;
			
			// aapt resource value: 0x7f060094
			public const int btnSchwAgrum = 2131099796;
			
			// aapt resource value: 0x7f060095
			public const int btnSchwTonic = 2131099797;
			
			// aapt resource value: 0x7f060096
			public const int btnSirop = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int btnSprite = 2131099799;
			
			// aapt resource value: 0x7f060048
			public const int btnSucreRoux = 2131099720;
			
			// aapt resource value: 0x7f06007a
			public const int btnTequila = 2131099770;
			
			// aapt resource value: 0x7f060036
			public const int btnTypeDeSoiree = 2131099702;
			
			// aapt resource value: 0x7f06007b
			public const int btnVB = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int btnVR = 2131099772;
			
			// aapt resource value: 0x7f06006e
			public const int btnValider = 2131099758;
			
			// aapt resource value: 0x7f06007d
			public const int btnVodka = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int btnWhisky = 2131099774;
			
			// aapt resource value: 0x7f060016
			public const int cB1 = 2131099670;
			
			// aapt resource value: 0x7f06001f
			public const int cB10 = 2131099679;
			
			// aapt resource value: 0x7f060017
			public const int cB2 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int cB3 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int cB4 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int cB5 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int cB6 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int cB7 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int cB8 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int cB9 = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int cE1 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int cE2 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int cE3 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int cE4 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int cE5 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int cN1 = 2131099685;
			
			// aapt resource value: 0x7f06002e
			public const int cN10 = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int cN11 = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int cN12 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int cN13 = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int cN14 = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int cN15 = 2131099699;
			
			// aapt resource value: 0x7f060026
			public const int cN2 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int cN3 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int cN4 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int cN5 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int cN6 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int cN7 = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int cN8 = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int cN9 = 2131099693;
			
			// aapt resource value: 0x7f060039
			public const int checkBox1 = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int checkBox2 = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int checkBox3 = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int checkBox4 = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int checkBox5 = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int checkBox6 = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int checkBox7 = 2131099711;
			
			// aapt resource value: 0x7f06006c
			public const int editCP = 2131099756;
			
			// aapt resource value: 0x7f060068
			public const int editMail = 2131099752;
			
			// aapt resource value: 0x7f06006b
			public const int editNom = 2131099755;
			
			// aapt resource value: 0x7f060069
			public const int editPass = 2131099753;
			
			// aapt resource value: 0x7f06006a
			public const int editPrenom = 2131099754;
			
			// aapt resource value: 0x7f060081
			public const int editText1 = 2131099777;
			
			// aapt resource value: 0x7f060082
			public const int editText2 = 2131099778;
			
			// aapt resource value: 0x7f060080
			public const int gallery1 = 2131099776;
			
			// aapt resource value: 0x7f06007f
			public const int gallery2 = 2131099775;
			
			// aapt resource value: 0x7f060088
			public const int linearLayout1 = 2131099784;
			
			// aapt resource value: 0x7f060000
			public const int mail = 2131099648;
			
			// aapt resource value: 0x7f06006d
			public const int majorite = 2131099757;
			
			// aapt resource value: 0x7f060001
			public const int sms = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int textView1 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int textView2 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int textView3 = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int textView4 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int textView5 = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Amis = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Calendrier = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Choix = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Config_soiree = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int coursesBoissons = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int coursesExtras = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int coursesNourriture = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Creer_sa_soiree = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int extras = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int foodApero = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int foodBarbecue = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int foodBrunch = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Invites = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Layout2 = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ListeAlcool = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Main = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Menu_Principal = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Soft = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Soirees = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Type_de_soiree = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int Login = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
